export const PROJECTS_REQUEST = 'PROJECTS_REQUEST';
export const PROJECTS_REQUEST_SUCCESS = 'PROJECTS_REQUEST_SUCCESS';
export const PROJECTS_REQUEST_FAILURE = 'PROJECTS_REQUEST_FAILURE';
export const PROJECTS_CHANGE_CURRENT = 'PROJECTS_CHANGE_CURRENT';
export const PROJECT_ADD_MONEY_REQUEST = 'PROJECT_ADD_MONEY_REQUEST';
export const PROJECT_ADD_MONEY_COMPLETED = 'PROJECT_ADD_MONEY_COMPLETED';